apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8s-terraria-server.fullname" . }}-data
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
