apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-terraria-server.fullname" . }}
  labels:
    {{- include "k8s-terraria-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
  selector:
    {{- include "k8s-terraria-server.selectorLabels" . | nindent 4 }}
